#!/usr/bin/env bash

# To get list of links use add-on "URLs List"
# $1 - file with links

dirname="linksload_$(date +"%s")"

wget -q -i <(cat $1 | grep -E "*.(png|jpg|jpeg|mp4|webm|gif)$" | sort | \
    uniq) -P $dirname
